version: '3.7'

services:
  node-server:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./source:/home/node/app/source
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: myApp
    expose:
      - '3000'
    ports:
      - '3000:3000'
    command: npm run dev
